apiVersion: apps/v1
kind: Deployment
metadata:
  name: highperfasr-stream
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: highperfasr-batch
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
