apiVersion: v1
kind: Service
metadata:
  name: highperfasr-batch
  labels:
    app: highperfasr-batch
spec:
  type: ClusterIP
  selector:
    app: highperfasr-batch
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: highperfasr-stream
  labels:
    app: highperfasr-stream
spec:
  type: ClusterIP
  selector:
    app: highperfasr-stream
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
